import java.awt.Color;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import twitter4j.IDs;
import twitter4j.Status;
import twitter4j.TwitterException;



/**
 *
 * @author lenovo
 */
public class status_fetch extends javax.swing.JFrame implements Runnable{
    Thread t = new Thread(this);
    twitter4j.Twitter twitter = null;
    String human = "";
    /**
     * Creates new form staus_fetch
     */
    
    public status_fetch(twitter4j.Twitter twt) throws TwitterException{
        initComponents();
        this.setResizable(false);
        this.setSize(705, 385);
        
        AutoCompleteDecorator.decorate(jComboBox1);
        AutoCompleteDecorator.decorate(jComboBox2);
        jSlider1.setValue(1);
        jSlider1.setMaximum(5);
        jSlider1.setMinimum(1);
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setPaintTicks(true);
        jSlider1.setPaintLabels(true);
        jRadioButton1.setSelected(true);
        twitter = twt;
        if(twitter!=null)
        {
            IDs followersIDs = twt.getFollowersIDs(-1);
            IDs friendsIDs = twt.getFriendsIDs(-1);
            for(long id: followersIDs.getIDs())
            {
               jComboBox1.addItem(twt.showUser(id).getName()+" - "+id);
            }
            for(long id: friendsIDs.getIDs())
            {
                jComboBox2.addItem(twt.showUser(id).getName()+" - "+id);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SENTIMENTAL ANALYSIS");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATES FETCH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 11, 690, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Get updates from TWITTER account of my:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 54, 690, 17);

        jComboBox1.setBackground(new java.awt.Color(0, 153, 204));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setOpaque(false);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(370, 89, 320, 30);

        jComboBox2.setBackground(new java.awt.Color(0, 153, 204));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setOpaque(false);
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(370, 130, 320, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Since last (x) days:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 178, 116, 17);

        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
        jSlider1.setOpaque(false);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(430, 178, 260, 50);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("FETCH");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 250, 90, 32);

        jLabel6.setBackground(new java.awt.Color(51, 153, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setToolTipText("Online / Offline");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(442, 332, 248, 17);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(10, 335, 321, 14);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Friend");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(10, 92, 63, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Follower");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(10, 133, 75, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/twit.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void run()
    {
        while(true)
        {
            try {
                Process prc = java.lang.Runtime.getRuntime().exec("ping www.twitter.com");
                int x = prc.waitFor();
                if(x==0)
                {
                    if(!jLabel6.getText().equals("Connected to internet!"))
                    {
                        jLabel6.setForeground(Color.blue);
                        jLabel6.setText("Connected to internet!");
                    }
                }
                else
                {
                    jLabel6.setForeground(Color.red);
                    jLabel6.setText("Internet access not available!");
                    JOptionPane.showMessageDialog(this, "Internet access required!");
                }
            } catch (InterruptedException | IOException ex) {
                Logger.getLogger(status_fetch.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setEnabled(false);
        //String name = "";
        try {
            // TODO add your handling code here:
            jProgressBar1.setIndeterminate(true);
            String name = "";
            if(jRadioButton1.isSelected())
            {
                name = (String) jComboBox1.getSelectedItem();
            }
            if(jRadioButton2.isSelected())
            {
                name = (String) jComboBox2.getSelectedItem();
            }
            int x = name.indexOf("-");
            human = name.substring(0, x-1);

            long id = Long.parseLong(name.substring(x+2, name.length()));
            Date currentDate = new Date();
            long difference = 0;
            long days = 0;
            List<Status> st = twitter.getUserTimeline(id);
            String fullString = "";
            for(Status stat: st)
            {
                difference = currentDate.getTime()-stat.getCreatedAt().getTime();
                days = TimeUnit.DAYS.convert(difference, TimeUnit.MILLISECONDS);
                if(!stat.getText().startsWith("RT") && days<=jSlider1.getValue())
                    fullString += stat.getText();
            }
            System.out.println(jSlider1.getValue());
            jProgressBar1.setIndeterminate(false);

            new ibm_tone(fullString,human).setVisible(true);
            
            this.setVisible(false);
            
        } 
        catch (TwitterException e) 
        {
            JOptionPane.showMessageDialog(this, "Exception: "+e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        t.start(); 
    }//GEN-LAST:event_formWindowOpened

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() != ItemEvent.SELECTED)
        {
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(true);
        }
        else
        {
            jComboBox2.setEnabled(false);
            jComboBox1.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() != ItemEvent.SELECTED)
        {
            jComboBox2.setEnabled(false);
            jComboBox1.setEnabled(true);
        }
        else
        {
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(status_fetch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(status_fetch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(status_fetch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(status_fetch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new status_fetch(null).setVisible(true);
                } catch (TwitterException ex) {
                    System.out.println("Exception: "+ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
